apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  namespace : jiyean-ns
spec:
  replicas: 2
  selector:
    # matchLabels: Replicaset이 관리해야할 파드를 결정하는데 사용
    matchLabels:
      app: my-nginx
  template:
    metadata:
      # labels: Pod들이 파생되는 label, 서비스에서 라우팅 할 대상이 되는 label, Service의 selector.app과 일치해야함
      labels:
        app: my-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: jiyean-ns
spec:
  type : ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: my-nginx